package com.example.mm.utils.database;

public enum DatabaseQueriesNames {
    GET_USERID_FROM_USERNAME,
    GET_ALL_PRODUCTS,
    GET_ALL_PRODUCTS_BY_PRICE_ASC,
    GET_ALL_PRODUCTS_BY_PRICE_DESC,
    GET_PRODUCTS_BY_NAME,
    GET_CART_PRODUCTS_FOR_USER,
    GET_LAST_CART_ID_FOR_USER,
    GET_PRODUCT_BY_ID,
    GET_ALL_USERS,
    GET_NUMBER_OF_LINES_IN_CART_FOR_PRODUCT,
    BUILD_NEW_CART_FOR_USER,
    ADD_PRODUCT_TO_CART,
    INCREASE_PRODUCT_QUANTITY_IN_CART,
    CHANGE_PRODUCT_QUANTITY_IN_CART,
    DELETE_PRODUCT_FROM_CART,
    GET_USER_ID_AND_PASSWORD_FROM_USERNAME,
    BUILD_USER_FROM_USERNAME_AND_PASSWORD,
    BUILD_USER_INVOICE
}

